[package]
name = "lowering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# source code locations
codespan = "0.11"
# fancy error messages
miette = "5"
thiserror = "1"
# big integers
num-bigint = "0.4"
# workspace members
parser = { path = "../parser" }
data = { path = "../../util/data" }
syntax = { path = "../syntax" }
miette_util = { path = "../../util/miette_util" }
