[package]
name = "printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty = { version = "0.11", features = ["termcolor"] }
# workspace members
parser = { path = "../parser" }
syntax = { path = "../syntax" }
data = { path = "../../util/data" }
